const D={
forest:{name:"숲 생태계",icon:"🌳",desc:"나무와 다양한 동물이 함께 살아가는 생태계",org:[
["oak","참나무","🌳","햇빛으로 양분을 만들어요.","producer"],["fern","고사리","🌿","숲 바닥에서 자라는 식물이에요.","producer"],["squirrel","다람쥐","🐿️","열매와 씨앗을 먹어요.","consumer"],["caterpillar","애벌레","🐛","식물의 잎을 먹어요.","consumer"],["bird","새","🐦","애벌레 등을 먹어요.","consumer"],["fox","여우","🦊","여러 동물을 먹어요.","consumer"],["mushroom","버섯","🍄","죽은 생물을 분해해요.","decomposer"]],abi:[["sun","햇빛","☀️"],["water","물","💧"],["soil","흙","🟫"],["rock","돌","🪨"],["temp","온도","🌡️"]],eats:{squirrel:["oak"],caterpillar:["oak","fern"],bird:["caterpillar"],fox:["squirrel","bird"],mushroom:["oak","fern"]}},
river:{name:"강 생태계",icon:"🌊",desc:"물이 흐르는 곳에서 생물이 살아가는 생태계",org:[
["algae","물풀·조류","🌿","물속의 생산자예요.","producer"],["reeds","갈대","🌾","강가에서 자라는 식물이에요.","producer"],["minnow","피라미","🐟","작은 생물을 먹어요.","consumer"],["tadpole","올챙이","🐸","물속에서 생활해요.","consumer"],["frog","개구리","🐸","곤충 등을 먹어요.","consumer"],["heron","왜가리","🦢","물고기와 개구리를 먹어요.","consumer"],["otter","수달","🦦","물고기 등을 먹어요.","consumer"],["microbe","분해 미생물","🦠","죽은 생물을 분해해요.","decomposer"]],abi:[["water","강물","💧"],["sun","햇빛","☀️"],["sand","모래","🟨"],["pebble","자갈","🪨"],["temp","온도","🌡️"]],eats:{minnow:["algae"],tadpole:["algae"],frog:["tadpole"],heron:["minnow","frog"],otter:["minnow"],microbe:["algae","reeds"]}},
ocean:{name:"바다 생태계",icon:"🌊",desc:"바닷물 속에서 다양한 생물이 살아가는 생태계",org:[
["phyto","식물플랑크톤","🦠","바다 생태계의 생산자예요.","producer"],["seaweed","해조류","🌿","햇빛으로 양분을 만들어요.","producer"],["zoo","동물플랑크톤","🦐","식물플랑크톤 등을 먹어요.","consumer"],["fish","작은 물고기","🐟","플랑크톤 등을 먹어요.","consumer"],["turtle","바다거북","🐢","해조류 등을 먹어요.","consumer"],["seal","물범","🦭","물고기 등을 먹어요.","consumer"],["shark","상어","🦈","다른 동물을 먹어요.","consumer"],["microbe","분해 미생물","🦠","죽은 생물을 분해해요.","decomposer"]],abi:[["water","바닷물","💧"],["sun","햇빛","☀️"],["salt","소금","🧂"],["sand","모래","🟨"],["temp","온도","🌡️"]],eats:{zoo:["phyto"],fish:["zoo"],turtle:["seaweed"],seal:["fish"],shark:["seal","fish"],microbe:["seaweed","fish"]}}
};
let S=JSON.parse(localStorage.getItem("ecoS")||"null")||{step:1,eco:null,sel:[],biotic:[],roles:{producer:[],consumer:[],decomposer:[]},rel:[],placed:[],name:""};
const $=id=>document.getElementById(id), E=()=>D[S.eco], find=id=>E().org.find(x=>x[0]===id)||E().abi.find(x=>x[0]===id);
function save(){localStorage.setItem("ecoS",JSON.stringify(S))}
function go(n){S.step=n;save();render()}
function toast(t){let x=$("toast");x.textContent=t;x.classList.add("show");setTimeout(()=>x.classList.remove("show"),1500)}
function shell(h,p,b,a=""){ $("screen").innerHTML=`<section class="hero"><h1>${h}</h1><p>${p}</p></section>${b}${a}`;$("stepText").textContent=S.step+" / 7";$("progressBar").style.width=S.step/7*100+"%"}
function render(){if(S.step===1)return one();if(S.step===2)return two();if(S.step===3)return three();if(S.step===4)return four();if(S.step===5)return five();if(S.step===6)return six();seven()}
function one(){shell("🧭 어디의 생태계를 탐험해 볼까요?","숲 · 강 · 바다 중 하나를 골라 탐험을 시작해 보세요.",`<div class="map"><div class="map-title">🌏 생태계 탐험 지도</div><div class="map-art">🌳　🌊　🐟　🌲　🐦</div></div><div class="cards">${Object.entries(D).map(([k,v])=>`<div class="eco-card ${S.eco===k?"selected":""}" onclick="pick('${k}')"><div class="eco-icon">${v.icon}</div><h3>${v.name}</h3><p>${v.desc}</p></div>`).join("")}</div>`,`<div class="actions"><button class="btn primary" ${S.eco?"":"disabled"} onclick="go(2)">다음 단계 →</button></div>`)}
function pick(k){S={...S,eco:k,sel:[],biotic:[],roles:{producer:[],consumer:[],decomposer:[]},rel:[],placed:[]};save();render()}
function two(){shell(`${E().icon} ${E().name}의 생물을 찾아보세요`,`마음에 드는 생물을 눌러 선택하세요. 선택한 생물 ${S.sel.length}개`,`<div class="panel"><div class="organism-grid">${E().org.map(o=>`<div class="org-card ${S.sel.includes(o[0])?"selected":""}" onclick="tog('${o[0]}')"><div class="org-photo">${o[2]}</div><div class="org-info"><span class="org-name">${o[1]}</span><span class="check">${S.sel.includes(o[0])?"✓":"＋"}</span><div class="org-desc">${o[3]}</div></div></div>`).join("")}</div></div>`,`<div class="actions"><button class="btn secondary" onclick="go(1)">← 이전</button><button class="btn primary" ${S.sel.length<3?"disabled":""} onclick="go(3)">다음 →</button></div>`)}
function tog(id){S.sel=S.sel.includes(id)?S.sel.filter(x=>x!==id):[...S.sel,id];save();render()}
function chip(id){let x=find(id);return `<div class="chip" draggable="true" ondragstart="drag(event,'${id}')">${x[2]} ${x[1]}</div>`}
function drag(e,id){e.dataTransfer.setData("text/plain",id)}
function three(){let un=S.sel.filter(id=>!S.biotic.includes(id)).map(chip).join("");let bi=S.biotic.map(chip).join("");let abi=E().abi.map(a=>`<div class="chip">${a[2]} ${a[1]}</div>`).join("");shell("🔬 생물 요소와 비생물 요소","카드를 알맞은 곳으로 끌어다 놓아 보세요.",`<div class="panel"><div class="classify-wrap"><div class="dropzone" ondragover="event.preventDefault()" ondrop="dropBio(event)"><h3>🌱 생물 요소</h3><div class="chips">${bi}</div></div><div class="dropzone"><h3>☀️ 비생물 요소</h3><div class="chips">${abi}</div></div></div><div style="margin-top:20px"><b>아직 분류하지 않은 생물</b><div class="chips" style="margin-top:10px">${un||"모두 분류했어요!"}</div></div></div>`,`<div class="actions"><button class="btn secondary" onclick="go(2)">← 이전</button><button class="btn primary" onclick="go(4)">다음 →</button></div>`)}
function dropBio(e){let id=e.dataTransfer.getData("text/plain");if(!S.biotic.includes(id))S.biotic.push(id);save();render()}
function four(){let un=S.biotic.filter(id=>!Object.values(S.roles).flat().includes(id)).map(chip).join("");let rc=(r,t,i)=>`<div class="role ${r}" ondragover="event.preventDefault()" ondrop="dropRole(event,'${r}')"><h3>${i} ${t}</h3><div class="chips">${S.roles[r].map(chip).join("")||"여기로 끌어주세요"}</div></div>`;shell("🍃 생태계에서 어떤 역할을 할까요?","생물 요소를 생산자·소비자·분해자로 분류해 보세요.",`<div class="panel"><div class="role-grid">${rc("producer","생산자","🌱")}${rc("consumer","소비자","🐿️")}${rc("decomposer","분해자","🍄")}</div><hr style="border:0;border-top:1px solid #dfe8e3;margin:25px 0"><b>분류하지 않은 생물</b><div class="chips" style="margin-top:10px">${un||"모두 분류했어요!"}</div></div>`,`<div class="actions"><button class="btn secondary" onclick="go(3)">← 이전</button><button class="btn primary" onclick="go(5)">다음 →</button></div>`)}
function dropRole(e,r){let id=e.dataTransfer.getData("text/plain");Object.keys(S.roles).forEach(k=>S.roles[k]=S.roles[k].filter(x=>x!==id));S.roles[r].push(id);save();render()}
function five(){let nodes=S.biotic.map(id=>{let o=find(id);return `<div class="web-node ${S.from===id?"active":""}" onclick="food('${id}')"><div class="web-emoji">${o[2]}</div><b>${o[1]}</b></div>`}).join("");let rs=S.rel.map(r=>`<span class="relation">${find(r[0])[1]} → ${find(r[1])[1]}</span>`).join("");shell("🕸️ 먹이 관계를 연결해 보세요","먼저 먹히는 생물을 누르고, 다음에 그것을 먹는 생물을 눌러 보세요.",`<div class="foodweb"><div class="web-instruction">예: 🌿 식물 → 🐛 애벌레 → 🐦 새</div><div class="web-grid">${nodes}</div><div class="relations"><b>내가 만든 먹이 관계</b><div>${rs||"아직 연결한 관계가 없어요."}</div></div></div>`,`<div class="actions"><button class="btn secondary" onclick="go(4)">← 이전</button><button class="btn primary" onclick="go(6)">다음 →</button></div>`)}
function food(id){if(!S.from){S.from=id;render();return}let a=S.from,b=id;S.from=null;if(E().eats[b]?.includes(a)){if(!S.rel.some(r=>r[0]===a&&r[1]===b))S.rel.push([a,b]);toast("✅ 먹이 관계를 찾았어요!")}else toast("음식 관계를 다시 생각해 볼까요?");save();render()}
function six(){let tools=S.sel.map(id=>{let o=find(id);return `<button class="tool-item" draggable="true" ondragstart="placeStart(event,'${id}')">${o[2]} ${o[1]}</button>`}).join("")+E().abi.map(a=>`<button class="tool-item" draggable="true" ondragstart="placeStart(event,'${a[0]}')">${a[2]} ${a[1]}</button>`).join("");let ps=S.placed.map((p,i)=>`<div class="placed" style="left:${p.x}px;top:${p.y}px">${p.emoji}<span>${p.name}</span></div>`).join("");shell("🌏 나만의 생태계를 만들어 보세요","왼쪽 요소를 생태계 안으로 끌어다 놓고, 그림도 그려 보세요.",`<div class="builder"><div class="toolbox"><h3>🌱 생물·비생물</h3>${tools}<div class="draw-controls"><button onclick="mode='pen'">✏️</button><button onclick="mode='erase'">🧽</button><button onclick="clearCanvas()">지우기</button></div></div><div class="canvas-wrap"><div class="ecosystem-canvas" id="canvasBox" ondragover="event.preventDefault()" ondrop="placeDrop(event)"><div class="canvas-ground"></div><canvas class="draw-layer" id="draw"></canvas>${ps}</div></div></div>`,`<div class="actions"><button class="btn secondary" onclick="go(5)">← 이전</button><button class="btn primary" onclick="go(7)">완성! →</button></div>`);setTimeout(canvasInit,0)}
function placeStart(e,id){e.dataTransfer.setData("place",id)}
function placeDrop(e){let id=e.dataTransfer.getData("place"),o=find(id),r=e.currentTarget.getBoundingClientRect();S.placed.push({id,name:o[1],emoji:o[2],x:e.clientX-r.left-20,y:e.clientY-r.top-25});save();render()}
let ctx,down=false,mode="pen";
function canvasInit(){let c=$("draw"),b=$("canvasBox");if(!c)return;c.width=b.clientWidth;c.height=b.clientHeight;ctx=c.getContext("2d");ctx.lineWidth=4;ctx.lineCap="round";c.onpointerdown=e=>{down=true;ctx.beginPath();ctx.moveTo(e.offsetX,e.offsetY)};c.onpointermove=e=>{if(!down)return;ctx.globalCompositeOperation=mode==="erase"?"destination-out":"source-over";ctx.lineTo(e.offsetX,e.offsetY);ctx.stroke()};c.onpointerup=()=>down=false}
function clearCanvas(){if(ctx)ctx.clearRect(0,0,$("draw").width,$("draw").height)}
function seven(){let cards=Object.entries(S.roles).map(([r,ids])=>`<div class="summary-card"><h3>${r==="producer"?"🌱 생산자":r==="consumer"?"🐿️ 소비자":"🍄 분해자"}</h3>${ids.map(id=>find(id)[1]).join(" · ")||"없음"}</div>`).join("");shell("🎉 탐험 완료!","이름을 적고 나의 생태계 탐험 결과를 제출해 보세요.",`<div class="panel"><div class="form"><b>학생 이름</b><input class="input" id="name" value="${S.name}" placeholder="이름을 입력하세요"><div class="summary">${cards}</div><div class="summary-card"><h3>🕸️ 먹이 관계</h3>${S.rel.map(r=>find(r[0])[1]+" → "+find(r[1])[1]).join("<br>")||"연결한 관계가 없어요."}</div></div></div>`,`<div class="actions"><button class="btn secondary" onclick="go(6)">← 이전</button><button class="btn primary" onclick="submitIt()">제출하기</button></div>`)}
function submitIt(){let n=$("name").value.trim();if(!n)return toast("이름을 입력해 주세요.");S.name=n;save();$("screen").innerHTML=`<div class="panel success"><div>🌿✨</div><h1>${n}의 탐험 결과가 저장되었어요!</h1><p>현재 1차 버전은 이 기기의 브라우저에 결과를 저장합니다.</p><button class="btn secondary" onclick="localStorage.removeItem('ecoS');location.reload()">처음부터 다시 하기</button></div>`;$("stepText").textContent="완료";$("progressBar").style.width="100%"}
render();